/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Kontrol.Koneksi;
import Kontrol.UserLogin;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author ASUS
 */

public class login extends javax.swing.JFrame {
    
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }
     Connection konek = Koneksi.getConnection();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addUser = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tmbLogin = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cekPass = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        addPass = new javax.swing.JPasswordField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(245, 220, 169));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 170, 138));
        jLabel2.setText("Selamat Datang ");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 130, 20));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 170, 138));
        jLabel3.setText("Username");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 20));

        addUser.setBackground(new java.awt.Color(245, 220, 169));
        addUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addUser.setBorder(null);
        jPanel3.add(addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 220, 30));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 170, 138));
        jLabel4.setText("Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, 20));

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LOGIN");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 80, 40));

        tmbLogin.setBackground(new java.awt.Color(255, 255, 255));
        tmbLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/nyerah.png"))); // NOI18N
        tmbLogin.setBorder(null);
        tmbLogin.setContentAreaFilled(false);
        tmbLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbLoginActionPerformed(evt);
            }
        });
        jPanel3.add(tmbLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 220, 60));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/biji.png"))); // NOI18N
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 110, 140));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/wa.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 190));

        cekPass.setBackground(new java.awt.Color(245, 220, 169));
        cekPass.setFont(new java.awt.Font("Verdana", 1, 9)); // NOI18N
        cekPass.setForeground(new java.awt.Color(241, 170, 138));
        cekPass.setText("show password");
        cekPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekPassActionPerformed(evt);
            }
        });
        jPanel3.add(cekPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 170, 138));
        jLabel6.setText("di Kopi Baen");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 220, 2));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 220, 2));

        addPass.setBackground(new java.awt.Color(245, 220, 169));
        addPass.setBorder(null);
        jPanel3.add(addPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 220, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekPassActionPerformed
        // TODO add your handling code here:
        if(cekPass.isSelected()){
            addPass.setEchoChar((char)0);
        }else{
            addPass.setEchoChar('*');
        }
    }//GEN-LAST:event_cekPassActionPerformed

    private void tmbLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbLoginActionPerformed
        // TODO add your handling code here:
        login();
        
    }//GEN-LAST:event_tmbLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField addPass;
    private javax.swing.JTextField addUser;
    private javax.swing.JCheckBox cekPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton tmbLogin;
    // End of variables declaration//GEN-END:variables
    
    public void login()
    {
        utama u = new utama();
        pemesanan order = new pemesanan();
        ResultSet RS;
        
       if(addUser.getText().isEmpty() || addPass.getText().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane,"Username dan Password Harus Di Isi","Peringatan",JOptionPane.WARNING_MESSAGE);
        addUser.requestFocus();
       } else {
        
        String username = addUser.getText();
        String password = addPass.getText();
        
        
        try{
            Statement state = konek.createStatement();
            // koneksi ke database
            String sql = "SELECT * FROM user where username='" + username 
                    + "' AND password='" + password + "'";
            RS = state.executeQuery(sql);
            JOptionPane.showMessageDialog(null, "Selamat Datang " 
                        + username + " !");
            // percabangan
            if(RS.next()){  // input benar
                u.namaAdm.setText(RS.getString("username"));
                u.isiID.setText(RS.getString("id_user"));
                u.hakAkses.setText(RS.getString("posisi"));
                u.info.setText(u.hakAkses.getText());
                
                UserLogin.setUserId(RS.getString("id_user"));
                UserLogin.setUsername(RS.getString("username"));
                                                                                                
                switch (RS.getString("posisi")) {
                    case "Admin":
                        u.setVisible(true);
                        this.dispose();
                        break;
                    case "Owner":
                        u.setVisible(true);
                        u.btnOrder.setVisible(false);
                        u.btnPayment.setVisible(false);
                        u.btnLaporan.setVisible(true);
                        break;
                    default:
                        u.setVisible(false);
                        JOptionPane.showMessageDialog(null, "Anda Tidak Terdaftar Dalam Sistem Ini");
                        break;              
                }
                
                
            }else{  // input salah
                JOptionPane.showMessageDialog(null, "Username dan Password Salah. Silahkan Coba Lagi !");
                addUser.setText(null);
                addPass.setText(null);
                addUser.requestFocus();
            }
        }catch(SQLException e){
            System.out.println(e);
        }
    }
}
}
