/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ASUS
 */

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import Kontrol.Koneksi;

public class Menu extends javax.swing.JFrame {

    
    /**
     * Creates new form menu
     */
    public Menu() {
        initComponents();
        close();
        tabelKopi();
        
    }
    
    Statement stat;
    Connection konek = Koneksi.getConnection();
    ResultSet RS;
    DefaultComboBoxModel modelc;
    DefaultTableModel model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        isiID = new javax.swing.JTextField();
        nmKopi = new javax.swing.JTextField();
        isiHarga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        peringatan = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKopi = new javax.swing.JTable();

        jInternalFrame1.setVisible(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel1.setText("Daftar Menu Kopi");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(289, 273, 139, -1));

        isiID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiIDActionPerformed(evt);
            }
        });
        jPanel1.add(isiID, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 108, 176, 30));
        jPanel1.add(nmKopi, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 148, 176, 30));

        isiHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isiHargaActionPerformed(evt);
            }
        });
        isiHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                isiHargaKeyTyped(evt);
            }
        });
        jPanel1.add(isiHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 186, 176, 30));

        jLabel3.setText("ID Kopi");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 116, -1, -1));

        jLabel4.setText("Nama Kopi");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 156, -1, -1));

        jLabel5.setText("Harga");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 194, -1, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel1.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 144, 118, 31));

        btnRefresh.setText("Refresh");
        btnRefresh.setBorder(null);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 217, 239, 33));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 48));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Input Menu Kopi");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 66, -1, 30));

        peringatan.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        peringatan.setForeground(new java.awt.Color(255, 51, 51));
        peringatan.setText("*Masukan Angka Semua");
        jPanel1.add(peringatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 222, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.setBorder(null);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 144, 114, 31));

        btnBatal.setText("Batal");
        btnBatal.setBorder(null);
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel1.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(484, 181, 239, 33));
        jPanel1.add(jScrollBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(723, 300, -1, 300));

        tblKopi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKopi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKopiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblKopi);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 713, 459));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isiHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiHargaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_isiHargaActionPerformed

    private void isiIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isiIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isiIDActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        
        String idKopi = isiID.getText();
        String namaKopi = nmKopi.getText();
        String Harga = isiHarga.getText();
        

        try{
            konek.createStatement().executeUpdate("INSERT INTO kopi VALUES ('"+idKopi+"','"+namaKopi+"','"+Harga+"')");
            JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal menyimpan!");
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
       resetForm();
       btnSimpan.setEnabled(true);
       
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void isiHargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_isiHargaKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_isiHargaKeyTyped

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        try{
            konek.createStatement().executeUpdate("DELETE FROM "
                    + "kopi WHERE harga='"+isiHarga.getText()+"'");
            JOptionPane.showMessageDialog(null, "Sukses Menghapus Data");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal");
        }
        // methos refresh
        resetForm();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        try {
            konek.createStatement().executeUpdate("DELETE FROM kopi WHERE harga = '"+isiHarga.getText()+"'");
            JOptionPane.showMessageDialog(null, "Simpan dibatalkan");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal membatalkan");
        }
    }//GEN-LAST:event_btnBatalActionPerformed

    private void tblKopiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKopiMouseClicked
        // TODO add your handling code here:
        int a = this.tblKopi.getSelectedRow();

        String idKopi = (String) model.getValueAt(a, 0);
        this.isiID.setText(idKopi);
        String namaKopi = (String) model.getValueAt(a, 1);
        this.nmKopi.setText(namaKopi);
        String Harga = (String) model.getValueAt(a, 2);
        this.isiHarga.setText(Harga);
    }//GEN-LAST:event_tblKopiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField isiHarga;
    private javax.swing.JTextField isiID;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nmKopi;
    private javax.swing.JLabel peringatan;
    private javax.swing.JTable tblKopi;
    // End of variables declaration//GEN-END:variables

    public void close()
    {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    private void tabelKopi()
    {
        String[] judul = {"ID_Kopi", "Nama Kopi", "Harga"};
        model = new DefaultTableModel(judul,0);
        tblKopi.setModel(model);
        String sql = "SELECT * FROM kopi";
        
        try {
            RS = konek.createStatement().executeQuery(sql);
            while(RS.next())
            {
                String idKopi = RS.getString("id_kopi");
                String namaKopi = RS.getString("nama_kopi");
                String Harga = RS.getString("harga");
                
                String[] data = {idKopi, namaKopi, Harga};
                model.addRow(data);
            }
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    public void resetForm()
    {
        isiID.setText("");
        nmKopi.setText("");
        isiHarga.setText("");
        
        tabelKopi();
        btnSimpan.setEnabled(true);
        isiID.setEnabled(true);
        nmKopi.setEnabled(true);
        isiHarga.setEnabled(true);
        
    }
}


