/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ASUS
 */

import Kontrol.UserLogin;
import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JFrame;
import Kontrol.set_transaksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class pembayaran extends javax.swing.JFrame {

    DefaultTableModel DTM;
    set_transaksi strans;
    String idTrans, idUser, idOrder, tanggal, namaCust;
    int total, bayar, kembalian;
    
    // Convert Rupiah
    DecimalFormat indo = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
    
    /**
     * Creates new form pembayaran
     */
    public pembayaran() {
        initComponents();
        close();
        jam();
        reset();
        strans = new set_transaksi();
        txtIDAdmin.setEnabled(false);
        txtIDOrder.setEnabled(false);
        txtCari.requestFocus();
        lblTanggal.setText(new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date()));
        txtIDAdmin.setText(UserLogin.getUserId());
        // Rupiah
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        indo.setDecimalFormatSymbols(formatRp);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBayar = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIDOrder = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtIDAdmin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtJumlahdibayarkan = new javax.swing.JTextField();
        lblkem = new javax.swing.JLabel();
        txtKembalian = new javax.swing.JTextField();
        btnBayar = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        lblJam = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTanggal.setText("-");
        jPanel1.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 80, -1));

        tblBayar.setBackground(new java.awt.Color(198, 139, 89));
        tblBayar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Order", "ID Kopi", "Nama Customer", "Jumlah"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBayarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBayar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 119, -1, 312));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("TRANSAKSI PEMBAYARAN");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 11, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 40));

        jLabel2.setText("Silahkan input ID order untuk proses pembayaran");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 449, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Cari ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 487, -1, -1));

        jLabel4.setText("ID Order :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 488, -1, -1));

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 481, 145, 28));

        jLabel5.setText("ID Admin");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 133, -1, -1));
        jPanel1.add(txtIDOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 183, 140, 33));

        jLabel6.setText("ID Order");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 192, -1, -1));
        jPanel1.add(txtIDAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 124, 139, 33));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL BAYAR");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 262, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 323, -1, 3));

        jLabel8.setText("Rp :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 303, -1, -1));

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotal.setText("-");
        jPanel1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 303, 130, -1));

        jLabel10.setText("Jumlah yang dibayarkan");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 350, -1, -1));

        txtJumlahdibayarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahdibayarkanActionPerformed(evt);
            }
        });
        txtJumlahdibayarkan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumlahdibayarkanKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJumlahdibayarkanKeyTyped(evt);
            }
        });
        jPanel1.add(txtJumlahdibayarkan, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 375, 191, 30));

        lblkem.setText("Kembalian");
        jPanel1.add(lblkem, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 411, -1, -1));

        txtKembalian.setEditable(false);
        jPanel1.add(txtKembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 431, 191, 30));

        btnBayar.setText("BAYAR");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 472, 191, 33));

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, 190, 30));

        lblJam.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        lblJam.setText("-");
        jPanel1.add(lblJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 70, -1));

        tgl.setText("Tanggal : ");
        jPanel1.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 72, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBayarMouseClicked
        // TODO add your handling code here:
        txtJumlahdibayarkan.setEnabled(true);
        txtJumlahdibayarkan.requestFocus();
        txtIDOrder.setText(tblBayar.getValueAt(tblBayar.getSelectedRow(),1) .toString());
//        total();
        
    }//GEN-LAST:event_tblBayarMouseClicked

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        simpanData();
    }//GEN-LAST:event_btnBayarActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        tampil();
    }//GEN-LAST:event_txtCariKeyReleased

    private void txtJumlahdibayarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahdibayarkanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtJumlahdibayarkanActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtJumlahdibayarkanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahdibayarkanKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(Character.isAlphabetic(enter)){
            evt.consume();
            txtKembalian.setText("Inputan harus angka");
            lblkem.setVisible(false);

        } 
    }//GEN-LAST:event_txtJumlahdibayarkanKeyTyped

    private void txtJumlahdibayarkanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumlahdibayarkanKeyReleased
        // TODO add your handling code here:
        if (!txtJumlahdibayarkan.getText().equalsIgnoreCase("")) {
            bayar = Integer.parseInt(txtJumlahdibayarkan.getText());
            total = Integer.parseInt(lblTotal.getText());
            kembalian = bayar-total;
            
            if (kembalian < 0) {
                lblkem.setVisible(false);
                txtKembalian.setText("Jumlah uang kurang");
                btnBayar.setEnabled(false);
            }else{
                lblkem.setVisible(true);
                txtKembalian.setText(String.valueOf(+kembalian));
                btnBayar.setEnabled(true);

            }
        }
    }//GEN-LAST:event_txtJumlahdibayarkanKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblkem;
    private javax.swing.JTable tblBayar;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField txtCari;
    public javax.swing.JTextField txtIDAdmin;
    private javax.swing.JTextField txtIDOrder;
    private javax.swing.JTextField txtJumlahdibayarkan;
    private javax.swing.JTextField txtKembalian;
    // End of variables declaration//GEN-END:variables

    public void close()
    {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public void jam()
    {
        Timer t = new Timer();
        t.scheduleAtFixedRate(new TimerTask(){
            
            @Override
            public void run(){
                lblJam.setText(new SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
            }
        },0,1000);
    }
    
    private void tampil()
    {
        DTM = (DefaultTableModel) tblBayar.getModel();
        DTM.setRowCount(0);
        // RAI
        try {
            if (strans.cekId(txtCari.getText())) {
                JOptionPane.showMessageDialog(null, "ID " +txtCari.getText()+" SUDAH DIBAYAR");
                txtCari.setText(null);
                return;
            }
        } catch (SQLException ex) {
            Logger.getLogger(pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        strans.tampil(DTM, txtCari.getText());
        tblBayar.setModel(DTM);
        if (DTM.getRowCount() > 0) {
            total();
            txtIDOrder.setText(txtCari.getText());
            txtJumlahdibayarkan.setEnabled(true);
            namaCust = DTM.getValueAt(0, 2).toString();
        } else {
            txtIDOrder.setText(null);
            lblTotal.setText(null);
            txtJumlahdibayarkan.setText(null);
            txtJumlahdibayarkan.setEnabled(false);
            txtKembalian.setText(null);
            btnBayar.setEnabled(false);
        }
    }
    
    private void total() 
    {
        try { 
//            ResultSet RS = strans.total(tblBayar.getValueAt(tblBayar.getSelectedRow(), 1).toString());
            ResultSet RS = strans.total(txtCari.getText());
            if (RS.next()) {
                lblTotal.setText(String.valueOf(RS.getInt("total")));
            }  
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error: Gagal");
        }
    }
    
    private void simpanData()
    {
        idUser = txtIDAdmin.getText();
        idOrder = txtIDOrder.getText();
        tanggal = lblTanggal.getText();
        total = Integer.parseInt(lblTotal.getText());
        
        strans.simpandata(idUser, idOrder, namaCust, tanggal, total);
        JOptionPane.showMessageDialog(null, "ID " +txtIDOrder.getText()+" TERBAYAR");
        btnBayar.setEnabled(false);
        
    }
    
    private void reset()
    {
        DefaultTableModel model = (DefaultTableModel) tblBayar.getModel();
        model.setRowCount(0);
        txtCari.setText(null);
        txtIDOrder.setText(null);
        lblTotal.setText(null);
        txtJumlahdibayarkan.setText(null);
        txtJumlahdibayarkan.setEnabled(false);
        txtKembalian.setText(null);
        btnBayar.setEnabled(false);
        txtCari.requestFocus();
    }
}

