/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author ASUS
 */

import java.util.Timer;
import java.util.TimerTask;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import Kontrol.Koneksi;
import Kontrol.UserLogin;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import Kontrol.set_kopi;
import Kontrol.set_pemesanan;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class pemesanan extends javax.swing.JFrame {
    set_kopi sk;
    set_pemesanan sp;
    String id_detail_pesanan, id_order, tanggal, jumlah, namaCust, idUser, id_kopi, nama_kopi;
    SimpleDateFormat today = new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat todayFormatSQL = new SimpleDateFormat("yyyy-MM-dd");
    
    /**
     * Creates new form pemesanan
     */
    public pemesanan() 
    {        
        initComponents();
        sk = new set_kopi();
        sp = new set_pemesanan();
        lblTanggal.setText(today.format(new java.util.Date()));
        
        close();
        jam();
        tabelKopi();
        isiIDOrder.setText("ORD-"+new SimpleDateFormat("mmss").format(new java.util.Date()));
        idAdmin.setEnabled(false);
        isiIDOrder.setEnabled(false);
        idAdmin.setText(UserLogin.getUserId());
        txtCari.requestFocus();
    }
    
    Statement stat;
    Connection konek = Koneksi.getConnection();
    DefaultTableModel model;


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        lblTanggal = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesan = new javax.swing.JTable();
        lblCari = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idAdmin = new javax.swing.JTextField();
        isiIDOrder = new javax.swing.JTextField();
        btnOrder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtKopi = new javax.swing.JLabel();
        txtNamaKopi = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        lblJml = new javax.swing.JLabel();
        isiJumlah = new javax.swing.JTextField();
        lblIDKopi = new javax.swing.JLabel();
        lblNamaKopi = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        isiNama = new javax.swing.JTextField();
        lblJam = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setToolTipText("");
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTanggal.setText("Tanggal :  -");
        jPanel3.add(lblTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 26, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Pilihan menu kopi ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 20));

        tblPesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblPesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesan);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, 320));

        lblCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCari.setText("Cari");
        jPanel3.add(lblCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 92, -1, -1));

        jLabel2.setText("ID_admin :");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        jLabel3.setText("ID_order :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        idAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAdminActionPerformed(evt);
            }
        });
        jPanel3.add(idAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 135, -1));
        jPanel3.add(isiIDOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 137, -1));

        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnOrder.setText("ORDER NOW");
        btnOrder.setBorder(null);
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        jPanel3.add(btnOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 423, 140, 32));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("|KETERANGAN");

        txtKopi.setText("ID_kopi");

        txtNamaKopi.setText("Nama_kopi");

        txtHarga.setText("Harga");

        lblJml.setText("Jumlah");

        lblIDKopi.setText("-");

        lblNamaKopi.setText("-");

        lblHarga.setText("-");

        lblNama.setText("Nama Customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNama)
                    .addComponent(txtKopi)
                    .addComponent(txtNamaKopi)
                    .addComponent(txtHarga)
                    .addComponent(jLabel6)
                    .addComponent(lblJml))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(isiJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(74, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(isiNama, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(lblNamaKopi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIDKopi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(isiJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblJml)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNama)
                            .addComponent(isiNama, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKopi)
                            .addComponent(lblIDKopi))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNamaKopi)
                            .addComponent(lblNamaKopi))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarga)
                            .addComponent(lblHarga))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 155, -1, 250));

        lblJam.setText("-");
        jPanel3.add(lblJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 11, 60, -1));

        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        jPanel3.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 137, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 910, 540));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ORDER");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 98, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("X");
        jButton2.setBorder(null);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 40, 42, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesanMouseClicked
        // TODO add your handling code here:
        int a = this.tblPesan.getSelectedRow(); // a adalah baris yang di klik
        
        String idKopi = (String) model.getValueAt(a, 0);
        this.lblIDKopi.setText(idKopi);
        String namaKopi = (String) model.getValueAt(a, 1);
        this.lblNamaKopi.setText(namaKopi);
        String Harga = (String) model.getValueAt(a, 2);
        this.lblHarga.setText(Harga);
    }//GEN-LAST:event_tblPesanMouseClicked

    private void idAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAdminActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        pesan();
    }//GEN-LAST:event_btnOrderActionPerformed

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        cari();
    }//GEN-LAST:event_txtCariKeyReleased

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrder;
    public javax.swing.JTextField idAdmin;
    private javax.swing.JTextField isiIDOrder;
    private javax.swing.JTextField isiJumlah;
    private javax.swing.JTextField isiNama;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCari;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblIDKopi;
    private javax.swing.JLabel lblJam;
    private javax.swing.JLabel lblJml;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaKopi;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JTable tblPesan;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtKopi;
    private javax.swing.JLabel txtNamaKopi;
    // End of variables declaration//GEN-END:variables

    public void close()
    {
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
     public void jam()
    {
        Timer t = new Timer();
        t.scheduleAtFixedRate(new TimerTask(){
            
            @Override
            public void run(){
                lblJam.setText(new SimpleDateFormat("HH:mm:ss").format(new java.util.Date()));
            }
        },0,1000);
    }
     
    public void tabelKopi()
    {
        // judul kolom
        String[] judul = {"ID Kopi", "Nama Kopi", "Harga"};
        model = new DefaultTableModel(judul,0);
        tblPesan.setModel(model);
        // koneksi ke database
        String sql = "SELECT * FROM kopi";
        
        try{
            ResultSet RS = konek.createStatement().executeQuery(sql);
            
            while(RS.next()){
                String idKopi = RS.getString("id_kopi");
                String namaKopi = RS.getString("nama_kopi");
                String Harga = RS.getString("harga");
                
                String[] data = {idKopi, namaKopi, Harga};
                model.addRow(data);
            }
        }catch(Exception e){
            System.out.println(e);
        }       
    }
    
    public void pesan()
    {
        id_order = isiIDOrder.getText();
        idUser = idAdmin.getText();
        namaCust = isiNama.getText();
        jumlah = isiJumlah.getText();
        isiNama.setEditable(false);
        try {
            tanggal = todayFormatSQL.format(today.parse(lblTanggal.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(pemesanan.class.getName()).log(Level.SEVERE, null, ex);
        }
        id_kopi = lblIDKopi.getText();
        nama_kopi = lblNamaKopi.getText();
        
        
        if(isiIDOrder.getText().isEmpty() ||
            lblIDKopi.getText().isEmpty() ||
            isiNama.getText().isEmpty() ||
            lblHarga.getText().isEmpty() ||
            isiJumlah.getText().isEmpty() ||
            lblNamaKopi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Data Harus Di Isi Semua", "Peringatan", JOptionPane.WARNING_MESSAGE);
            
        }else {
            try {
                Boolean isExist = sp.cekId(id_order);
                if(!isExist){
                    sp.dataPesanan(id_order, tanggal, jumlah, namaCust, idUser);
                }
                
                sp.detailPesanan(id_order, id_kopi, jumlah, namaCust);
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null, "Gagal");
            }
           
            JOptionPane.showMessageDialog(rootPane,"Pesanan Berhasil di Input","Sukses",JOptionPane.INFORMATION_MESSAGE);
            
        }
    }
    
    public void cari()
    {
        String cari = txtCari.getText();
        DefaultTableModel DTM = (DefaultTableModel)tblPesan.getModel();
        DTM.setRowCount(0);
        sk.caridata(DTM, cari);
        tblPesan.setModel(DTM);
    }
    
    private void reset()
    {
        isiIDOrder.setText(null);
        idAdmin.setText(null);
        isiNama.setText(null);
        lblIDKopi.setText(null);
        lblNamaKopi.setText(null);
        lblHarga.setText(null);
        isiJumlah.setText(null);
        
    }
    
}


